<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_CG_CreateGist</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>572fecff-3a0b-470a-9fbe-9099c74a624d</testSuiteGuid>
   <testCaseLink>
      <guid>b3df0d6b-8f92-449c-bb4f-92898c5a638d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_CG_CreateGist</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fc924d8-9aae-4115-b7bf-7805d6c3031d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6577c77-533d-4fbb-b00e-7fdf071e722f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4065c29-ba7e-46ef-b50f-60f17f72baee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0fcc78b2-a726-4d6d-8244-7b251e9fa8c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_CG_EditGist</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a90c6e26-8750-429b-82f1-c7caee111e9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d16f7d2-6d72-4e20-a241-cf37f334489c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8e4cd9d-7ddc-4a47-9b37-f8c9bd345f97</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b92b48ba-1baa-4127-b309-bfc1ea21a676</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>22f6d694-e6a3-4b1e-bd94-e3c7031a1fb6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_CG_DeleteGist</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18abf064-1676-49c4-bb40-225ea01d82d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b3a9c33-fca8-4f97-85a2-e73186d053ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4e1e05a-bf07-4ce2-8250-8b7dd729ba2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>854d241c-ddf3-4ac8-a751-76d6c609fa6a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>411e2497-b8ee-438b-9d6b-80851a64bce4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_CG_ViewGistList</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
